# Generated by Django 3.2.7 on 2021-10-16 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurantId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=128)),
                ('cuisine', models.CharField(max_length=32)),
                ('rating', models.FloatField()),
                ('totalRatings', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='RecoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your name', max_length=32)),
                ('age', models.PositiveIntegerField(default=18, help_text='Enter your age')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', help_text='Sex', max_length=1)),
                ('address', models.CharField(help_text='Enter your address', max_length=128)),
                ('phone', models.CharField(help_text='Enter your mobile number of 10 digits', max_length=10)),
                ('diet', models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non Veg'), ('N/P', 'No Preference')], default='N/P', help_text='Select type of Diet', max_length=32)),
                ('region', models.CharField(choices=[('North', 'North'), ('South', 'South'), ('East', 'East'), ('West', 'West'), ('North-East', 'North-East'), ('Chinese', 'Chinese'), ('Western', 'Western'), ('N/P', 'No Preference')], default='N/P', help_text='Select your region', max_length=32)),
                ('state', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal', 'Himachal'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('N/P', 'No Preference')], default='N/P', help_text='Select your state', max_length=32)),
                ('flavour', models.CharField(choices=[('Sweet', 'Sweet'), ('Spicy', 'Spicy'), ('Sour', 'Sour'), ('Bitter', 'Bitter'), ('N/P', 'No Preference')], default='N/P', help_text='Which flavour do you prefer?', max_length=32)),
                ('ingredient', models.CharField(help_text='Enter your ingredient preference', max_length=128)),
                ('RUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='menuItem',
            fields=[
                ('itemId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=128)),
                ('price', models.IntegerField()),
                ('rating', models.FloatField()),
                ('category', models.CharField(max_length=32)),
                ('diet', models.CharField(max_length=32)),
                ('restaurantId', models.ForeignKey(help_text='Enter ID', on_delete=django.db.models.deletion.CASCADE, to='Reco.restaurant')),
            ],
        ),
    ]
