# Generated by Django 3.2.7 on 2021-10-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reco', '0003_alter_menuitem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
