# Generated by Django 3.2.7 on 2021-10-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reco', '0007_alter_recouser_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recouser',
            name='ingredient',
            field=models.CharField(help_text='Enter your ingredient preferences separated by commas', max_length=128),
        ),
    ]
