# Generated by Django 3.2.7 on 2021-11-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reco', '0009_menuitem_numratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='link',
            field=models.IntegerField(default=-1),
        ),
    ]
