# Generated by Django 3.2.7 on 2021-11-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reco', '0011_auto_20211116_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='features',
            field=models.JSONField(default=list),
        ),
    ]
