# Generated by Django 3.2.7 on 2021-11-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reco', '0012_menuitem_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='recouser',
            name='recentfeature',
            field=models.JSONField(default=list),
        ),
    ]
