# Generated by Django 3.2.7 on 2021-12-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reco', '0014_auto_20211129_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='recouser',
            name='satList',
            field=models.JSONField(default=list),
        ),
    ]
